"""Static reference catalogue of every SOAP/OData SAP Business ByDesign
(and closely related) integration this app talks to - built for a public,
no-login internal reference page (user's explicit ask, Sep 18 2026).

Endpoint URLs below are copied straight from backend/.env at doc-build
time - update this file if a Communication Arrangement endpoint ever
changes. Never add credentials here; only usernames (never passwords) are
named, purely to distinguish which technical/business user each call uses.
"""

TENANT_HOST = "my431827.businessbydesign.cloud.sap"

INTEGRATIONS = [
    # ---------------------------------------------------------------- Inbound / GRN
    {
        "id": "sap_inbound_delivery_notification_client",
        "name": "Standard Inbound Delivery Notification",
        "category": "Inbound / Goods Receipt",
        "protocol": "SOAP",
        "service": "ManageStandardInboundDeliveryNotificationIn",
        "endpoint_env": "SAP_SOAP_INBOUND_DELIVERY_NOTIFICATION_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/managestandardinbounddeliveryn?sap-vhost={TENANT_HOST}",
        "operations": ["CheckMaintainBundle", "MaintainBundle (release=True)"],
        "technical_user": "_EMERGENTBOM (SOAP technical user)",
        "purpose": "Creates + releases a Goods Receipt directly against a supplier Purchase Order, with the actual received quantity set at creation. Replaces the older Playwright PO-search-and-post-receipt UI flow.",
        "status": "active",
        "client_file": "sap_inbound_delivery_notification_client.py",
    },
    {
        "id": "sap_gsa_write_client",
        "name": "Goods and Service Acknowledgement (write)",
        "category": "Inbound / Goods Receipt",
        "protocol": "SOAP",
        "service": "ManageGoodsAndServiceAcknowledgementIn",
        "endpoint_env": "SAP_SOAP_GSA_WRITE_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/managegoodsandserviceacknowle1?sap-vhost={TENANT_HOST}",
        "operations": ["post_goods_receipt"],
        "technical_user": "_EMERGENTBOM (SOAP technical user)",
        "purpose": "Posts a Goods Receipt against a PO for non-stock/service lines only - confirmed a dead end for real stock materials, which is why the Inbound Delivery Notification service above + Playwright below exist.",
        "status": "active (service PO lines only)",
        "client_file": "sap_gsa_write_client.py",
    },
    {
        "id": "sap_gsa_client",
        "name": "Goods and Service Acknowledgement (read)",
        "category": "Inbound / Goods Receipt",
        "protocol": "SOAP",
        "service": "QueryGoodsAndServiceAcknowledgementInbound",
        "endpoint_env": "SAP_SOAP_GSA_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/querygoodsandserviceacknowled1?sap-vhost={TENANT_HOST}",
        "operations": ["FindSimpleByElements"],
        "technical_user": "_EMERGENTBOM (SOAP technical user)",
        "purpose": "Reads the real physical goods-receipt date for a Product ID, straight from SAP (separate document from Supplier Invoice).",
        "status": "active",
        "client_file": "sap_gsa_client.py",
    },
    {
        "id": "sap_inbound_delivery_report_client",
        "name": "Inbound Delivery Detailed Details (analytics)",
        "category": "Inbound / Goods Receipt",
        "protocol": "OData (Business Analytics report)",
        "service": "RPZ9645E136D1191FF78E36A7QueryResults",
        "endpoint_env": "SAP_INBOUND_DELIVERY_REPORT_ODATA_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/ana_businessanalytics_analytics.svc/RPZ9645E136D1191FF78E36A7QueryResults",
        "operations": ["find_confirmation_rows"],
        "technical_user": "SAP_ODATA_BUSINESS_USER (business user)",
        "purpose": "Recovers the real Inbound Delivery ID for a PO from SAP's own report when Playwright automation silently missed capturing it.",
        "status": "active",
        "client_file": "sap_inbound_delivery_report_client.py",
    },
    {
        "id": "sap_inbound_delivery_client",
        "name": "Inbound STO Receipt (custom OData)",
        "category": "Inbound / Goods Receipt",
        "protocol": "OData (custom service)",
        "service": "inboundstockemergent",
        "endpoint_env": "SAP_ODATA_INBOUND_BASE_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/inboundstockemergent",
        "operations": ["find_delivery_by_id", "update_item_quantity", "release_delivery", "post_goods_receipt"],
        "technical_user": "n/a",
        "purpose": "Built to post Goods Receipt for an inbound Stock Transfer delivery notification.",
        "status": "provisioned, not currently wired into any live flow",
        "client_file": "sap_inbound_delivery_client.py",
    },
    {
        "id": "sap_playwright_supplier_pgr_service",
        "name": "Supplier PO Goods Receipt (UI automation)",
        "category": "Inbound / Goods Receipt - deprecated path",
        "protocol": "Playwright (headless SAP UI automation)",
        "service": "Inbound Logistics work center - Purchase Orders view",
        "endpoint_env": "n/a (drives the SAP web UI directly)",
        "endpoint_url": f"https://{TENANT_HOST}/",
        "operations": ["search PO", "Post Goods Receipt", "fill Delivery Notification ID/date/qty", "Save and Close"],
        "technical_user": "SAP_UI_USERNAME_2/3 (pooled UI login)",
        "purpose": "Fallback for real stock material GRNs where the API GSA-write path is a confirmed dead end. Being phased out in favour of API paths wherever SAP allows it.",
        "status": "dormant fallback, kept as-is per user's explicit ask",
        "client_file": "sap_playwright_supplier_pgr_service.py",
    },
    {
        "id": "sap_playwright_pgr_service",
        "name": "Inbound Delivery Notification Goods Receipt (UI automation)",
        "category": "Inbound / Goods Receipt - deprecated path",
        "protocol": "Playwright (headless SAP UI automation)",
        "service": "Inbound Delivery Notification screen",
        "endpoint_env": "n/a (drives the SAP web UI directly)",
        "endpoint_url": f"https://{TENANT_HOST}/",
        "operations": ["Post Goods Receipt"],
        "technical_user": "SAP_UI_USERNAME_2/3 (pooled UI login)",
        "purpose": "Used only where SAP's own InboundDeliveryPGRBackground custom OData action is confirmed disabled for this tenant.",
        "status": "dormant fallback, kept as-is per user's explicit ask",
        "client_file": "sap_playwright_pgr_service.py",
    },

    # ---------------------------------------------------------------- Outbound / Stock Transfer
    {
        "id": "sap_sto_client",
        "name": "Manage Customer Requirements (Stock Transfer Order)",
        "category": "Outbound / Stock Transfer",
        "protocol": "SOAP",
        "service": "ManageCustomerRequirementIn",
        "endpoint_env": "SAP_SOAP_STO_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/managecustomerrequirementin?sap-vhost={TENANT_HOST}",
        "operations": ["check (CheckMaintainAsBundle)", "maintain (MaintainAsBundle)"],
        "technical_user": "_EMERGENTBOM (SOAP technical user)",
        "purpose": "Creates real Intra-Company Stock Transfer Orders. Always runs a Check before every real Maintain.",
        "status": "active",
        "client_file": "sap_sto_client.py",
    },
    {
        "id": "sap_outbound_delivery_client",
        "name": "Outbound Delivery / Goods Issue (custom OData)",
        "category": "Outbound / Stock Transfer",
        "protocol": "OData (custom service)",
        "service": "odataoutboundemergent",
        "endpoint_env": "BYD_ODATA_BASE",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/odataoutboundemergent",
        "operations": ["find_delivery_request_items", "find_outbound_delivery_ids/objects", "release_outbound_delivery (OutboundDeliveryRelease)", "post_goods_issue (PGIInBackground)", "post_goods_issue_schedule_line (SLPGIInBackground)", "request_delivery_execution (SLRequestDeliveryExecution)"],
        "technical_user": "SAP_USERNAME (itadmin business user)",
        "purpose": "Finds the Outbound Delivery Request SAP produces from a Stock Transfer Order and automates Goods Issue / Release wherever an API path exists. Single-line orders post fully via PGIInBackground; multi-line orders still need one manual 'Save' click in SAP's own Delivery Proposal screen (9 documented API attempts confirmed no way to automate that specific step - see module docstring).",
        "status": "active",
        "client_file": "sap_outbound_delivery_client.py",
    },
    {
        "id": "sap_outbound_delivery_analytics_client",
        "name": "Outbound Delivery Analytics",
        "category": "Outbound / Stock Transfer",
        "protocol": "OData (Business Analytics report)",
        "service": "RPSCMOBDB04_Q0001QueryResults",
        "endpoint_env": "SAP_INSTANCE_URL (report path built at runtime)",
        "endpoint_url": f"https://{TENANT_HOST}/",
        "operations": ["find_deliveries_for_sto"],
        "technical_user": "SAP_ODATA_USERNAME",
        "purpose": "Fast read of whether a Stock Transfer Order's Outbound Delivery has finished/matched quantities - replaces a fragile Playwright-based detection.",
        "status": "active",
        "client_file": "sap_outbound_delivery_analytics_client.py",
    },
    {
        "id": "sap_site_logistics_client",
        "name": "Site Logistics Task (Query + Manage)",
        "category": "Outbound / Stock Transfer",
        "protocol": "SOAP",
        "service": "QuerySiteLogisticsTaskIn / ManageSiteLogisticsTaskIn",
        "endpoint_env": "SAP_SOAP_QUERY_SITE_LOGISTICS_TASK_ENDPOINT / SAP_SOAP_MANAGE_SITE_LOGISTICS_TASK_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/querysitelogisticstaskin?sap-vhost={TENANT_HOST} , https://{TENANT_HOST}/sap/bc/srt/scs/sap/managesitelogisticstaskin?sap-vhost={TENANT_HOST}",
        "operations": ["find_tasks_for_site (FindByElements)", "confirm_tasks_bundle (MaintainBundle_V1)"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Investigated as attempt #8/#9 to automate the multi-line Delivery Proposal 'Save' step. Live-verified dead end: this tenant's Site Logistics Tasks are only ever created for a production material-issue/receipt scenario, never for Stock Transfer/Outbound Delivery.",
        "status": "dormant - confirmed not applicable to this use case",
        "client_file": "sap_site_logistics_client.py",
    },
    {
        "id": "sap_playwright_outbound_gi_service",
        "name": "Multi-line Outbound Delivery combine + Goods Issue (UI automation)",
        "category": "Outbound / Stock Transfer - deprecated path",
        "protocol": "Playwright (headless SAP UI automation)",
        "service": "Outbound Delivery Proposal screen",
        "endpoint_env": "n/a (drives the SAP web UI directly)",
        "endpoint_url": f"https://{TENANT_HOST}/",
        "operations": ["combine delivery proposal", "fill GST/logistics fields", "post Goods Issue"],
        "technical_user": "SAP_UI_USERNAME_2/3 (pooled UI login)",
        "purpose": "Superseded by the Manual Goods Issue architecture (Sep 18 2026) - staff now click 'Save and Release' themselves in SAP; this app only verifies the result via API. Code kept dormant per user's explicit ask, never invoked by any live flow.",
        "status": "dormant, superseded",
        "client_file": "sap_playwright_outbound_gi_service.py",
    },

    # ---------------------------------------------------------------- Production
    {
        "id": "sap_production_lot_client",
        "name": "Production Lot Query + Confirmation",
        "category": "Production",
        "protocol": "SOAP",
        "service": "QueryProductionLotISIIn / ManageProductionLotsIn",
        "endpoint_env": "SAP_SOAP_PRODUCTION_LOT_QUERY_ENDPOINT / SAP_SOAP_PRODUCTION_LOT_MANAGE_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/queryproductionlotisiin?sap-vhost={TENANT_HOST} , https://{TENANT_HOST}/sap/bc/srt/scs/sap/manageproductionlotsin?sap-vhost={TENANT_HOST}",
        "operations": ["find_open_lots", "find_lot_by_id", "confirm_reporting_point (MaintainBundle_V1)", "finish_task", "restart_task", "confirm_material_output", "create_material_output"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Lists open Production Lots/Reporting Points and posts real confirmations (quantity, scrap, deviation reason) against them.",
        "status": "active",
        "client_file": "sap_production_lot_client.py",
    },
    {
        "id": "sap_production_proposal_client",
        "name": "Production Proposal creation",
        "category": "Production",
        "protocol": "SOAP",
        "service": "ManageProductionProposalIn",
        "endpoint_env": "SAP_SOAP_PRODUCTION_PROPOSAL_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/manageproductionproposalin?sap-vhost={TENANT_HOST}",
        "operations": ["create_proposal (CreateBundle)"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Creates a Production Proposal (Material/Site/Qty/Date) which SAP's own planning run explodes into a Production Request/Order - SAP's only supported way to create production orders via web service.",
        "status": "active",
        "client_file": "sap_production_proposal_client.py",
    },
    {
        "id": "sap_production_order_release_client",
        "name": "Production Order / Planning Order release (custom OData)",
        "category": "Production",
        "protocol": "OData (custom service)",
        "service": "productionorderemergent / productionproposalemergent",
        "endpoint_env": "SAP_ODATA_PRODUCTION_ORDER_RELEASE_BASE_URL / SAP_ODATA_PRODUCTION_PROPOSAL_RELEASE_BASE_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/productionorderemergent , https://{TENANT_HOST}/sap/byd/odata/cust/v1/productionproposalemergent",
        "operations": ["release_order", "list_ids_by_status", "get_life_cycle_status", "is_released", "get_requested_material", "tag_with_proposal_id", "create_with_source_of_supply"],
        "technical_user": "SAP_ODATA_BUSINESS_USER",
        "purpose": "SAP has no standard SOAP/OData API to release a Production Order - this calls a custom OData action the user's SAP admin built via the Key User OData Modeler to expose that release action.",
        "status": "active",
        "client_file": "sap_production_order_release_client.py",
    },
    {
        "id": "sap_production_model_client",
        "name": "Source of Supply / Production Model lookup",
        "category": "Production",
        "protocol": "OData (custom service)",
        "service": "productionmodelemergent / productionmodelbomemergent",
        "endpoint_env": "SAP_ODATA_PRODUCTION_MODEL_BASE_URL / SAP_ODATA_PRODUCTION_MODEL_BOM_BASE_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/productionmodelemergent , https://{TENANT_HOST}/sap/byd/odata/cust/v1/productionmodelbomemergent",
        "operations": ["get_supply_planning_area_uuid", "get_source_of_supply_options", "get_bill_of_material_id_for_model", "get_bill_of_operations_id_for_model_id"],
        "technical_user": "SAP_ODATA_USERNAME",
        "purpose": "Reads which Production Model(s)/BOM/BOO apply to a Material at a given Supply Planning Area (site).",
        "status": "active",
        "client_file": "sap_production_model_client.py",
    },
    {
        "id": "sap_boo_client",
        "name": "Production Bill of Operations (Reporting Point names)",
        "category": "Production",
        "protocol": "SOAP",
        "service": "ManageProductionBillofOperationsIn",
        "endpoint_env": "SAP_SOAP_BOO_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/manageproductionbillofoperatio?sap-vhost={TENANT_HOST}",
        "operations": ["get_marker_element_descriptions (ReadProductionBillofOperations)"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Resolves a Reporting Point's technical code (e.g. 'RP_10') to its human-readable name (e.g. 'BLANK+PUNCH').",
        "status": "active",
        "client_file": "sap_boo_client.py",
    },
    {
        "id": "sap_wip_clearing_client",
        "name": "WIP Clearing Run",
        "category": "Production",
        "protocol": "SOAP",
        "service": "AccountingWIPClearingRun",
        "endpoint_env": "SAP_SOAP_WIP_CLEARING_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/accountingwipclearingrun?sap-vhost={TENANT_HOST}",
        "operations": ["run_wip_clearing (CreateWip)"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Zeroes out a Production Lot's work-in-process inventory for period-end reporting.",
        "status": "active",
        "client_file": "sap_wip_clearing_client.py",
    },
    {
        "id": "sap_cost_estimate_client",
        "name": "Material Cost Estimate Run",
        "category": "Production",
        "protocol": "SOAP",
        "service": "ManageMaterialCostEstimateRunDataBundle",
        "endpoint_env": "SAP_SOAP_COST_ESTIMATE_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/managematerialcostestimaterund?sap-vhost={TENANT_HOST}",
        "operations": ["run_cost_estimate"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Triggers a real Cost Estimate Run for a single Material so a sub-assembly shown only as a rolled-up cost in BOM Explorer can get an actual SAP-calculated Standard Cost on demand.",
        "status": "active",
        "client_file": "sap_cost_estimate_client.py",
    },
    {
        "id": "sap_goods_movement_client",
        "name": "Goods Movement (Store Approval issue stock)",
        "category": "Production",
        "protocol": "SOAP",
        "service": "InventoryProcessingGoodsAndActivityConfirmationGoodsMovementIn",
        "endpoint_env": "SAP_SOAP_GOODS_MOVEMENT_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/inventoryprocessinggoodsandac2?sap-vhost={TENANT_HOST}",
        "operations": ["goods_movement (DoGoodsMovement)"],
        "technical_user": "SAP_SOAP_USERNAME (_EMERGENTBOM)",
        "purpose": "Posts a direct stock issue for the Store Approval screen only - replaces the Radish QMS REST wrapper for this one action.",
        "status": "active",
        "client_file": "sap_goods_movement_client.py",
    },

    # ---------------------------------------------------------------- Purchase Order
    {
        "id": "sap_po_client",
        "name": "Purchase Order query (Supplier Portal)",
        "category": "Purchase Order",
        "protocol": "SOAP",
        "service": "QueryPurchaseOrderQueryIn",
        "endpoint_env": "SAP_SOAP_PO_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/querypurchaseorderqueryin?sap-vhost={TENANT_HOST}",
        "operations": ["fetch_recent_window", "fetch_backfill_chunk (PurchaseOrderSimpleByElementsQuery_sync)"],
        "technical_user": "SAP_SOAP_USERNAME (_EMERGENTBOM)",
        "purpose": "Lets an approved external vendor see their own open Purchase Orders inside the Supplier Portal.",
        "status": "active",
        "client_file": "sap_po_client.py",
    },
    {
        "id": "sap_po_odata_client",
        "name": "Purchase Order creation (custom OData)",
        "category": "Purchase Order",
        "protocol": "OData (custom service)",
        "service": "khpurchaseorder",
        "endpoint_env": "SAP_ODATA_PO_BASE_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/khpurchaseorder",
        "operations": ["create_purchase_order", "create_service_purchase_order", "list_gl_accounts"],
        "technical_user": "SAP_USERNAME (itadmin business user)",
        "purpose": "Creates real Purchase Orders. Replaced the standard ManagePurchaseOrderIn SOAP path below, which could never persist Business Residence/Purchasing Unit correctly.",
        "status": "active (primary PO creation path)",
        "client_file": "sap_po_odata_client.py",
    },
    {
        "id": "sap_po_write_client",
        "name": "Purchase Order write (SOAP, legacy)",
        "category": "Purchase Order",
        "protocol": "SOAP",
        "service": "ManagePurchaseOrderIn",
        "endpoint_env": "SAP_SOAP_PO_MANAGE_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/managepurchaseorderin?sap-vhost={TENANT_HOST}",
        "operations": ["cancel_purchase_order", "cancel_purchase_order_item", "release_purchase_order", "set_item_hsn_code", "get_purchase_order_status", "get_purchase_order_number"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Kept only for cancel/release/status/HSN-code actions on POs (not creation anymore - see sap_po_odata_client.py above).",
        "status": "active (non-creation actions only)",
        "client_file": "sap_po_write_client.py",
    },
    {
        "id": "sap_po_analytics_client",
        "name": "Purchase Order Analytics (open PO quantity)",
        "category": "Purchase Order",
        "protocol": "OData (Business Analytics report)",
        "service": "RPSRMPO_B02_Q0004QueryResults",
        "endpoint_env": "SAP_INSTANCE_URL (report path built at runtime)",
        "endpoint_url": f"https://{TENANT_HOST}/",
        "operations": ["fetch_open_po_quantities"],
        "technical_user": "SAP_ODATA_USERNAME",
        "purpose": "Reads real open-PO quantities per line item - replaced a cancelled Playwright-based reader per the user's explicit ask.",
        "status": "active",
        "client_file": "sap_po_analytics_client.py",
    },
    {
        "id": "sap_supplier_invoice_client",
        "name": "Supplier Invoice query",
        "category": "Purchase Order",
        "protocol": "SOAP",
        "service": "QuerySupplierInvoiceQueryIn",
        "endpoint_env": "SAP_SOAP_SUPPLIER_INVOICE_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/querysupplierinvoicequeryin?sap-vhost={TENANT_HOST}",
        "operations": ["get_invoices_for_product (FindSimpleByElements / QUERY_BY_ELEMENTS)"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Reads real posted Supplier Invoice line items for a Product ID (supplier, price, qty, date) as an authoritative cross-check against the external Price Explorer.",
        "status": "active",
        "client_file": "sap_supplier_invoice_client.py",
    },
    {
        "id": "sap_price_spec_client",
        "name": "Procurement Price Specification",
        "category": "Purchase Order",
        "protocol": "OData (custom service) + SOAP (write)",
        "service": "pricespecificationemergent / ManageProcurementPriceSpecific",
        "endpoint_env": "SAP_PRICE_SPEC_ODATA_BASE_URL / SAP_SOAP_PRICE_SPEC_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/pricespecificationemergent , https://{TENANT_HOST}/sap/bc/srt/scs/sap/manageprocurementpricespecific?sap-vhost={TENANT_HOST}",
        "operations": ["get_price_specs_for_product", "create_price_spec", "push_one"],
        "technical_user": "SAP_ODATA_USERNAME / SAP_SOAP_USERNAME",
        "purpose": "Reads/writes purchasing prices already maintained in SAP (SAP's equivalent of a Purchasing Info Record) for the Suppliers page.",
        "status": "active",
        "client_file": "sap_price_spec_client.py",
    },
    {
        "id": "sap_supplier_client",
        "name": "Supplier master query",
        "category": "Purchase Order",
        "protocol": "SOAP",
        "service": "QuerySupplierIn",
        "endpoint_env": "SAP_SOAP_SUPPLIER_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/querysupplierin1?sap-vhost={TENANT_HOST}",
        "operations": ["list_suppliers (FindSuppliers)"],
        "technical_user": "SAP_SOAP_USERNAME (_EMERGENTBOM)",
        "purpose": "Reads the Supplier master list (ID, UUID, name, contact, email, phone) to populate the Suppliers page from real SAP data.",
        "status": "active",
        "client_file": "sap_supplier_client.py",
    },
    {
        "id": "sap_supplier_manage_scripts",
        "name": "Supplier master write (SOAP, maintenance scripts)",
        "category": "Purchase Order",
        "protocol": "SOAP",
        "service": "ManageSupplierIn",
        "endpoint_env": "SAP_SOAP_SUPPLIER_MANAGE_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/managesupplierin1?sap-vhost={TENANT_HOST}",
        "operations": ["one-off maintenance writes (fix_supplier_contacts.py / update_suppliers.py)"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Used only by one-time data-fix scripts, not by any live app request path.",
        "status": "provisioned, script-only use",
        "client_file": "fix_supplier_contacts.py / update_suppliers.py",
    },

    # ---------------------------------------------------------------- Master Data
    {
        "id": "sap_material_client",
        "name": "Material ID -> UUID resolution",
        "category": "Master Data",
        "protocol": "SOAP",
        "service": "QueryMaterialIn",
        "endpoint_env": "SAP_SOAP_MATERIAL_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/querymaterialin?sap-vhost={TENANT_HOST}",
        "operations": ["resolve_material_info", "resolve_uuid", "get_uom_info", "get_existing_procurement_type_code"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Resolves a Material ID to its internal system UUID for products that never appear in a BOM (pure raw materials).",
        "status": "active",
        "client_file": "sap_material_client.py",
    },
    {
        "id": "sap_material_create_client",
        "name": "Material master creation + site activation",
        "category": "Master Data",
        "protocol": "SOAP",
        "service": "ManageMaterialIn",
        "endpoint_env": "SAP_SOAP_MATERIAL_MANAGE_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/managematerialin1?sap-vhost={TENANT_HOST}",
        "operations": ["create_material (MaintainBundle_V1, actionCode 01)", "delete_material", "activate_site"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Creates new Material master records and activates a Material for an additional Site (Planning/Availability/Logistics/Valuation).",
        "status": "active",
        "client_file": "sap_material_create_client.py",
    },
    {
        "id": "sap_material_valuation_data_client",
        "name": "Material Valuation Data (write)",
        "category": "Master Data",
        "protocol": "SOAP",
        "service": "ManageMaterialValuationDataIn",
        "endpoint_env": "SAP_SOAP_MATERIAL_VALUATION_MANAGE_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/managematerialvaluationdatain?sap-vhost={TENANT_HOST}",
        "operations": ["set_account_determination_and_price"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Sets Account Determination Group + Perpetual Cost Method + opening Valuation Price so a material's site activation can flip to Active.",
        "status": "active",
        "client_file": "sap_material_valuation_data_client.py",
    },
    {
        "id": "sap_material_physical_client",
        "name": "Material physical attributes (weight/area)",
        "category": "Master Data",
        "protocol": "OData (custom service)",
        "service": "materialgeneralinfo",
        "endpoint_env": "SAP_MATERIAL_GENERALINFO_ODATA_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/materialgeneralinfo",
        "operations": ["get_physical_attributes", "push_physical_attributes", "push_one"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Reads/writes custom fields (Item Net Weight, Surface Area, Item Gross Weight) the SAP admin added to the Material business object.",
        "status": "active",
        "client_file": "sap_material_physical_client.py",
    },
    {
        "id": "sap_planning_client",
        "name": "Material Supply Planning (Safety Stock / Lead Time)",
        "category": "Master Data",
        "protocol": "OData (custom service)",
        "service": "materialltmsl",
        "endpoint_env": "SAP_PLANNING_ODATA_BASE_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/materialltmsl",
        "operations": ["get_planning_data", "push_planning_data", "push_one"],
        "technical_user": "SAP_ODATA_USERNAME",
        "purpose": "Reads and writes Safety Stock / Procurement Lead Time per Material per Supply Planning Area (site).",
        "status": "active",
        "client_file": "sap_planning_client.py",
    },
    {
        "id": "sap_valuation_client",
        "name": "Material Valuation Data (read - Standard Costs)",
        "category": "Master Data",
        "protocol": "OData (custom service)",
        "service": "materialvaluationdata",
        "endpoint_env": "SAP_ODATA_BASE_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/cust/v1/materialvaluationdata",
        "operations": ["get_standard_costs"],
        "technical_user": "SAP_ODATA_USERNAME",
        "purpose": "Reads live Standard Cost / Moving Average price data, joined onto the BOM Explorer and Inventory pages.",
        "status": "active",
        "client_file": "sap_valuation_client.py",
    },
    {
        "id": "sap_hsn_client",
        "name": "HSN Code lookup (analytics)",
        "category": "Master Data",
        "protocol": "OData (Business Analytics report)",
        "service": "RPZ0947E2F59B1F629245246DQueryResults",
        "endpoint_env": "SAP_HSN_ODATA_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/ana_businessanalytics_analytics.svc/RPZ0947E2F59B1F629245246DQueryResults",
        "operations": ["get_hsn_codes"],
        "technical_user": "SAP_ODATA_USERNAME",
        "purpose": "Reads HSN Codes via a Business Analytics report - the direct Material/CustomerInvoice HSN fields are PSM-blocked from custom OData on this tenant.",
        "status": "active",
        "client_file": "sap_hsn_client.py",
    },
    {
        "id": "sap_fixed_asset_client",
        "name": "Fixed Asset master list",
        "category": "Master Data",
        "protocol": "SOAP",
        "service": "QueryObjectDescriptionIn (Object Type Code 176)",
        "endpoint_env": "SAP_SOAP_OBJECT_DESCRIPTION_ENDPOINT",
        "endpoint_url": f"https://{TENANT_HOST}/sap/bc/srt/scs/sap/queryobjectdescriptionin?sap-vhost={TENANT_HOST}",
        "operations": ["list_fixed_assets (FindObjectDescriptionByElements)"],
        "technical_user": "SAP_SOAP_USERNAME",
        "purpose": "Lists every real Fixed Asset master record so the Capital PO form can show a live dropdown instead of ever creating a new asset.",
        "status": "active",
        "client_file": "sap_fixed_asset_client.py",
    },

    # ---------------------------------------------------------------- Analytics / Reporting
    {
        "id": "sap_inventory_client",
        "name": "On-Hand Inventory (analytics)",
        "category": "Analytics / Reporting",
        "protocol": "OData (Business Analytics report - SCMINVV02)",
        "service": "RPZ76B8273872353FC8677FCFQueryResults",
        "endpoint_env": "SAP_INVENTORY_ODATA_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/ana_businessanalytics_analytics.svc/RPZ76B8273872353FC8677FCFQueryResults",
        "operations": ["get_on_hand_stock", "get_inventory_detail"],
        "technical_user": "SAP_ODATA_USERNAME",
        "purpose": "Reads live, company-wide on-hand stock quantities.",
        "status": "active",
        "client_file": "sap_inventory_client.py",
    },
    {
        "id": "sap_inventory_closing_client",
        "name": "Historical / Closing Inventory (analytics)",
        "category": "Analytics / Reporting",
        "protocol": "OData (Business Analytics report - RPFININVU14)",
        "service": "RPFININVU14_Q0001QueryResults",
        "endpoint_env": "SAP_INVENTORY_CLOSING_ODATA_URL",
        "endpoint_url": f"https://{TENANT_HOST}/sap/byd/odata/ana_businessanalytics_analytics.svc/RPFININVU14_Q0001QueryResults",
        "operations": ["get_closing_inventory"],
        "technical_user": "SAP_ODATA_USERNAME",
        "purpose": "Reads a true as-of-date inventory snapshot (company/plant-wise Qty and value) - the live On-Hand Inventory report has no historical archive.",
        "status": "active",
        "client_file": "sap_inventory_closing_client.py",
    },
]

CATEGORY_ORDER = [
    "Inbound / Goods Receipt",
    "Inbound / Goods Receipt - deprecated path",
    "Outbound / Stock Transfer",
    "Outbound / Stock Transfer - deprecated path",
    "Production",
    "Purchase Order",
    "Master Data",
    "Analytics / Reporting",
]


def get_sap_integrations_doc() -> dict:
    by_category = {}
    for item in INTEGRATIONS:
        by_category.setdefault(item["category"], []).append(item)
    ordered = [{"category": c, "integrations": by_category[c]} for c in CATEGORY_ORDER if c in by_category]
    counts = {
        "total": len(INTEGRATIONS),
        "active": sum(1 for i in INTEGRATIONS if i["status"].startswith("active")),
        "dormant_or_deprecated": sum(1 for i in INTEGRATIONS if "dormant" in i["status"] or "deprecated" in i["category"]),
        "soap": sum(1 for i in INTEGRATIONS if "SOAP" in i["protocol"]),
        "odata": sum(1 for i in INTEGRATIONS if "OData" in i["protocol"]),
        "playwright": sum(1 for i in INTEGRATIONS if "Playwright" in i["protocol"]),
    }
    return {"tenant_host": TENANT_HOST, "counts": counts, "categories": ordered}
